"""Generated response models. Import the public models from ``trustat.types`` or
the package root; ``models`` here is generated by datamodel-code-generator."""

from __future__ import annotations

from . import models
from ._base import TrustatModel

__all__ = ["TrustatModel", "models"]
