# generated by datamodel-codegen:
#   filename:  openapi_snapshot.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import Field
from trustat._models._base import TrustatModel


class AdCreative(TrustatModel):
    """
    Полная карточка рекламного креатива (одно объявление).
    """

    creative_hash: Annotated[str | None, Field(title='Creative Hash')] = None
    """
    Идентификатор креатива (ключ карточки)
    """
    title: Annotated[str | None, Field(title='Title')] = None
    """
    Заголовок / имя рекламодателя
    """
    message: Annotated[str | None, Field(title='Message')] = None
    """
    Текст объявления
    """
    button_text: Annotated[str | None, Field(title='Button Text')] = None
    """
    Текст кнопки-призыва (CTA)
    """
    color_id: Annotated[int | None, Field(title='Color Id')] = None
    """
    Акцентный цвет объявления (0–12), если задан
    """
    ad_format: Annotated[str | None, Field(title='Ad Format')] = None
    """
    Формат: «image», «premium_emoji», «text», «video»
    """
    advertiser_type: Annotated[str | None, Field(title='Advertiser Type')] = None
    """
    Тип рекламодателя: «website», «channel», «bot»
    """
    creative_lang: Annotated[str | None, Field(title='Creative Lang')] = None
    """
    Язык объявления (ISO 639, напр. «ru»)
    """
    target_url: Annotated[str | None, Field(title='Target Url')] = None
    """
    Целевая ссылка объявления (сайт или t.me)
    """
    target_domain: Annotated[str | None, Field(title='Target Domain')] = None
    """
    Целевой домен/канал, выведенный из ссылки (напр. «example.com» или «t.me/durov»)
    """
    target_type: Annotated[str | None, Field(title='Target Type')] = None
    """
    Тип цели: «website», «channel» или «bot»
    """
    media_url: Annotated[str | None, Field(title='Media Url')] = None
    """
    Ссылка на медиа объявления (картинка/видео)
    """
    media_thumb_url: Annotated[str | None, Field(title='Media Thumb Url')] = None
    """
    Ссылка на миниатюру медиа
    """
    advertiser_photo_url: Annotated[str | None, Field(title='Advertiser Photo Url')] = (
        None
    )
    """
    Аватар рекламодателя
    """
    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала, в котором замечено объявление
    """
    channel_country: Annotated[str | None, Field(title='Channel Country')] = None
    """
    Страна канала показа (нормализована)
    """
    channel_lang: Annotated[str | None, Field(title='Channel Lang')] = None
    """
    Язык канала показа
    """
    channel_category_id: Annotated[int | None, Field(title='Channel Category Id')] = (
        None
    )
    """
    Категория канала показа (справочник категорий)
    """
    first_seen: Annotated[str | None, Field(title='First Seen')] = None
    """
    Когда объявление впервые замечено, UTC ISO-8601
    """
    last_seen: Annotated[str | None, Field(title='Last Seen')] = None
    """
    Когда объявление замечено в последний раз, UTC ISO-8601
    """
    message_html: Annotated[str | None, Field(title='Message Html')] = None
    """
    HTML-версия текста объявления (для рендера)
    """
    advertised_channel_id: Annotated[
        int | None, Field(title='Advertised Channel Id')
    ] = None
    """
    ID рекламируемого канала, если цель — канал/бот (для перехода к его статистике)
    """


class AdSummary(TrustatModel):
    """
    Рекламный креатив Telegram Ads (карточка в списках).
    """

    creative_hash: Annotated[str | None, Field(title='Creative Hash')] = None
    """
    Идентификатор креатива (ключ карточки)
    """
    title: Annotated[str | None, Field(title='Title')] = None
    """
    Заголовок / имя рекламодателя
    """
    message: Annotated[str | None, Field(title='Message')] = None
    """
    Текст объявления
    """
    button_text: Annotated[str | None, Field(title='Button Text')] = None
    """
    Текст кнопки-призыва (CTA)
    """
    color_id: Annotated[int | None, Field(title='Color Id')] = None
    """
    Акцентный цвет объявления (0–12), если задан
    """
    ad_format: Annotated[str | None, Field(title='Ad Format')] = None
    """
    Формат: «image», «premium_emoji», «text», «video»
    """
    advertiser_type: Annotated[str | None, Field(title='Advertiser Type')] = None
    """
    Тип рекламодателя: «website», «channel», «bot»
    """
    creative_lang: Annotated[str | None, Field(title='Creative Lang')] = None
    """
    Язык объявления (ISO 639, напр. «ru»)
    """
    target_url: Annotated[str | None, Field(title='Target Url')] = None
    """
    Целевая ссылка объявления (сайт или t.me)
    """
    target_domain: Annotated[str | None, Field(title='Target Domain')] = None
    """
    Целевой домен/канал, выведенный из ссылки (напр. «example.com» или «t.me/durov»)
    """
    target_type: Annotated[str | None, Field(title='Target Type')] = None
    """
    Тип цели: «website», «channel» или «bot»
    """
    media_url: Annotated[str | None, Field(title='Media Url')] = None
    """
    Ссылка на медиа объявления (картинка/видео)
    """
    media_thumb_url: Annotated[str | None, Field(title='Media Thumb Url')] = None
    """
    Ссылка на миниатюру медиа
    """
    advertiser_photo_url: Annotated[str | None, Field(title='Advertiser Photo Url')] = (
        None
    )
    """
    Аватар рекламодателя
    """
    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала, в котором замечено объявление
    """
    channel_country: Annotated[str | None, Field(title='Channel Country')] = None
    """
    Страна канала показа (нормализована)
    """
    channel_lang: Annotated[str | None, Field(title='Channel Lang')] = None
    """
    Язык канала показа
    """
    channel_category_id: Annotated[int | None, Field(title='Channel Category Id')] = (
        None
    )
    """
    Категория канала показа (справочник категорий)
    """
    first_seen: Annotated[str | None, Field(title='First Seen')] = None
    """
    Когда объявление впервые замечено, UTC ISO-8601
    """
    last_seen: Annotated[str | None, Field(title='Last Seen')] = None
    """
    Когда объявление замечено в последний раз, UTC ISO-8601
    """


class AdvertiserAdsList(TrustatModel):
    """
    Объявления одного рекламодателя (по домену цели).
    """

    domain: Annotated[str | None, Field(title='Domain')] = None
    """
    Запрошенный домен цели
    """
    total: Annotated[int | None, Field(title='Total')] = None
    """
    Примерное число объявлений этого домена
    """
    limit: Annotated[int | None, Field(title='Limit')] = None
    """
    Размер страницы из запроса
    """
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    """
    Курсор следующей страницы
    """
    ads: Annotated[list[AdSummary] | None, Field(title='Ads')] = None
    """
    Объявления, ведущие на этот домен
    """


class CategoryDict(TrustatModel):
    id: Annotated[int | None, Field(title='Id')] = None
    """
    ID категории
    """
    name: Annotated[str | None, Field(title='Name')] = None
    """
    Название категории
    """
    channels_count: Annotated[int | None, Field(title='Channels Count')] = None
    """
    Сколько каналов в этой категории
    """


class ChannelAdsList(TrustatModel):
    """
    Реклама, замеченная в конкретном канале.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник канала: «telegram» или «max»
    """
    limit: Annotated[int | None, Field(title='Limit')] = None
    """
    Размер страницы из запроса
    """
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    """
    Курсор следующей страницы
    """
    ads: Annotated[list[AdSummary] | None, Field(title='Ads')] = None
    """
    Объявления, замеченные в этом канале
    """


class ChannelInfo(TrustatModel):
    """
    Публичная карточка канала.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала (Telegram или MAX)
    """
    title: Annotated[str | None, Field(title='Title')] = None
    """
    Название канала
    """
    username: Annotated[str | None, Field(title='Username')] = None
    """
    Юзернейм без «@» (если публичный)
    """
    canonical_link: Annotated[str | None, Field(title='Canonical Link')] = None
    """
    Канонический публичный линк: username или join-хеш приватного канала
    """
    about: Annotated[str | None, Field(title='About')] = None
    """
    Описание канала
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    peer_type: Annotated[str | None, Field(title='Peer Type')] = None
    """
    Тип: «channel» (канал) или «chat» (чат/группа)
    """
    participants: Annotated[int | None, Field(title='Participants')] = None
    """
    Число подписчиков
    """
    verified: Annotated[bool | None, Field(title='Verified')] = None
    """
    Верифицирован (официальная галочка)
    """
    scam: Annotated[bool | None, Field(title='Scam')] = None
    """
    Помечен платформой как скам
    """
    fake: Annotated[bool | None, Field(title='Fake')] = None
    """
    Помечен платформой как фейк
    """
    sensitive_photo: Annotated[bool | None, Field(title='Sensitive Photo')] = None
    """
    Аватар помечен как чувствительный контент
    """
    photo_url: Annotated[str | None, Field(title='Photo Url')] = None
    """
    URL аватара (полный размер)
    """
    photo_url_thumb: Annotated[str | None, Field(title='Photo Url Thumb')] = None
    """
    URL аватара (миниатюра)
    """
    lang: Annotated[str | None, Field(title='Lang')] = None
    """
    Код языка канала (ISO 639, напр. «ru»)
    """
    country: Annotated[str | None, Field(title='Country')] = None
    """
    Код страны (напр. «ru», «INTL»)
    """
    categories: Annotated[list[Any] | None, Field(title='Categories')] = None
    """
    Категории канала в виде [{id, name}]
    """


class ChannelList(TrustatModel):
    """
    Страница каталога/поиска каналов.
    """

    total: Annotated[int | None, Field(title='Total')] = None
    """
    Примерное число подходящих каналов (точно до порога; дальше — нижняя оценка)
    """
    limit: Annotated[int | None, Field(title='Limit')] = None
    """
    Размер страницы из запроса
    """
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    """
    Курсор следующей страницы; null, если каналов больше нет (или достигнут потолок глубины — сузьте фильтр)
    """
    channels: Annotated[list[ChannelInfo] | None, Field(title='Channels')] = None
    """
    Каналы на этой странице
    """


class ChannelStat(TrustatModel):
    """
    Ключевые метрики канала: аудитория, охваты, вовлечённость, динамика, упоминания, оценка качества.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    participants: Annotated[int | None, Field(title='Participants')] = None
    """
    Число подписчиков
    """
    views24: Annotated[int | None, Field(title='Views24')] = None
    """
    Средние просмотры поста за 24 часа
    """
    views48: Annotated[int | None, Field(title='Views48')] = None
    """
    Средние просмотры поста за 48 часов
    """
    views72: Annotated[int | None, Field(title='Views72')] = None
    """
    Средние просмотры поста за 72 часа
    """
    er24: Annotated[int | None, Field(title='Er24')] = None
    """
    Вовлечённость (ER) за 24 часа
    """
    er_day: Annotated[float | None, Field(title='Er Day')] = None
    """
    ER за день
    """
    er_yesterday: Annotated[float | None, Field(title='Er Yesterday')] = None
    """
    ER за вчера
    """
    er_week: Annotated[float | None, Field(title='Er Week')] = None
    """
    ER за неделю
    """
    er_month: Annotated[float | None, Field(title='Er Month')] = None
    """
    ER за месяц
    """
    er_year: Annotated[float | None, Field(title='Er Year')] = None
    """
    ER за год
    """
    er_day_diff: Annotated[float | None, Field(title='Er Day Diff')] = None
    """
    Изменение ER за день
    """
    er_week_diff: Annotated[float | None, Field(title='Er Week Diff')] = None
    """
    Изменение ER за неделю
    """
    er_month_diff: Annotated[float | None, Field(title='Er Month Diff')] = None
    """
    Изменение ER за месяц
    """
    er_year_diff: Annotated[float | None, Field(title='Er Year Diff')] = None
    """
    Изменение ER за год
    """
    day_growth: Annotated[int | None, Field(title='Day Growth')] = None
    """
    Прирост подписчиков за день
    """
    yesterday_growth: Annotated[int | None, Field(title='Yesterday Growth')] = None
    """
    Прирост подписчиков за вчера
    """
    week_growth: Annotated[int | None, Field(title='Week Growth')] = None
    """
    Прирост подписчиков за неделю
    """
    month_growth: Annotated[int | None, Field(title='Month Growth')] = None
    """
    Прирост подписчиков за месяц
    """
    year_growth: Annotated[int | None, Field(title='Year Growth')] = None
    """
    Прирост подписчиков за год
    """
    day_growth_percent: Annotated[float | None, Field(title='Day Growth Percent')] = (
        None
    )
    """
    Прирост подписчиков за день, %
    """
    week_growth_percent: Annotated[float | None, Field(title='Week Growth Percent')] = (
        None
    )
    """
    Прирост подписчиков за неделю, %
    """
    month_growth_percent: Annotated[
        float | None, Field(title='Month Growth Percent')
    ] = None
    """
    Прирост подписчиков за месяц, %
    """
    year_growth_percent: Annotated[float | None, Field(title='Year Growth Percent')] = (
        None
    )
    """
    Прирост подписчиков за год, %
    """
    total_mentions: Annotated[int | None, Field(title='Total Mentions')] = None
    """
    Всего упоминаний канала
    """
    day_mentions: Annotated[int | None, Field(title='Day Mentions')] = None
    """
    Упоминаний за день
    """
    week_mentions: Annotated[int | None, Field(title='Week Mentions')] = None
    """
    Упоминаний за неделю
    """
    month_mentions: Annotated[int | None, Field(title='Month Mentions')] = None
    """
    Упоминаний за месяц
    """
    year_mentions: Annotated[int | None, Field(title='Year Mentions')] = None
    """
    Упоминаний за год
    """
    quality_score: Annotated[float | None, Field(title='Quality Score')] = None
    """
    Оценка качества канала (0–100)
    """


class CountryDict(TrustatModel):
    code: Annotated[str | None, Field(title='Code')] = None
    """
    Код страны (напр. «ru», «INTL»)
    """
    channels_count: Annotated[int | None, Field(title='Channels Count')] = None
    """
    Сколько каналов с этой страной
    """


class EnvelopeAdCreative(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: AdCreative | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeAdvertiserAdsList(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: AdvertiserAdsList | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeChannelAdsList(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: ChannelAdsList | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeChannelInfo(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: ChannelInfo | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeChannelList(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: ChannelList | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeChannelStat(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: ChannelStat | None = None
    """
    Полезная нагрузка ответа
    """


class FacetBucket(TrustatModel):
    value: Annotated[str | int | None, Field(title='Value')] = None
    """
    Значение фасета
    """
    count: Annotated[int | None, Field(title='Count')] = None
    """
    Сколько объявлений с этим значением
    """


class Forward(TrustatModel):
    """
    Публикация, которая сделала репост из запрошенного канала.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала, опубликовавшего репост
    """
    message_id: Annotated[int | None, Field(title='Message Id')] = None
    """
    ID сообщения с репостом
    """
    post_id: Annotated[str | None, Field(title='Post Id')] = None
    """
    Идентификатор поста-репоста «<channel_id>_<message_id>»
    """
    date: Annotated[str | None, Field(title='Date')] = None
    """
    Дата поста-репоста, UTC ISO-8601
    """
    views: Annotated[int | None, Field(title='Views')] = None
    """
    Просмотры поста-репоста
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    original_channel_id: Annotated[int | None, Field(title='Original Channel Id')] = (
        None
    )
    """
    ID исходного канала (откуда переслали)
    """
    original_message_id: Annotated[int | None, Field(title='Original Message Id')] = (
        None
    )
    """
    ID исходного сообщения
    """
    original_post_id: Annotated[str | None, Field(title='Original Post Id')] = None
    """
    Идентификатор исходного поста «<channel_id>_<message_id>»
    """
    original_source: Annotated[str | None, Field(title='Original Source')] = None
    """
    Платформа исходного канала: «telegram» или «max»
    """


class ForwardList(TrustatModel):
    """
    Страница репостов из канала.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала-источника
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник запрошенного канала: «telegram» или «max»
    """
    total: Annotated[int | None, Field(title='Total')] = None
    """
    Всего найдено репостов
    """
    limit: Annotated[int | None, Field(title='Limit')] = None
    """
    Размер страницы из запроса
    """
    offset: Annotated[int | None, Field(title='Offset')] = None
    """
    Смещение из запроса
    """
    forwards: Annotated[list[Forward] | None, Field(title='Forwards')] = None
    """
    Посты, репостнувшие из этого канала
    """


class HealthStatus(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = None
    """
    Всегда «ok», если сервис жив
    """


class LanguageDict(TrustatModel):
    code: Annotated[str | None, Field(title='Code')] = None
    """
    Код языка (ISO 639, напр. «ru»)
    """
    channels_count: Annotated[int | None, Field(title='Channels Count')] = None
    """
    Сколько каналов на этом языке
    """


class LanguagesDict(TrustatModel):
    languages: Annotated[list[LanguageDict] | None, Field(title='Languages')] = None
    """
    Справочник языков
    """


class LookupResult(TrustatModel):
    """
    Канонический результат резолва идентификатора.
    """

    type: Annotated[str | None, Field(title='Type')] = None
    """
    «channel» или «post»
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Платформа: «telegram» или «max»
    """
    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    Внутренний ID канала
    """
    peer_type: Annotated[str | None, Field(title='Peer Type')] = None
    """
    Тип: «channel» (канал) или «chat» (чат/группа)
    """
    username: Annotated[str | None, Field(title='Username')] = None
    """
    Юзернейм, если есть
    """
    message_id: Annotated[int | None, Field(title='Message Id')] = None
    """
    ID сообщения (только для type=post)
    """
    canonical_link: Annotated[str | None, Field(title='Canonical Link')] = None
    """
    Канонический публичный линк канала
    """


class Mention(TrustatModel):
    """
    Упоминание канала другим каналом.
    """

    src_channel_id: Annotated[int | None, Field(title='Src Channel Id')] = None
    """
    ID канала-источника упоминания
    """
    src_message_id: Annotated[int | None, Field(title='Src Message Id')] = None
    """
    ID сообщения-источника
    """
    src_post_id: Annotated[str | None, Field(title='Src Post Id')] = None
    """
    Идентификатор поста-источника «<channel_id>_<message_id>»
    """
    src_source: Annotated[str | None, Field(title='Src Source')] = None
    """
    Платформа упоминающего поста: «telegram» или «max»
    """
    type: Annotated[str | None, Field(title='Type')] = None
    """
    Тип упоминания (напр. «link»)
    """
    post_date: Annotated[str | None, Field(title='Post Date')] = None
    """
    Дата упоминания, UTC ISO-8601
    """


class MentionList(TrustatModel):
    """
    Страница упоминаний канала.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала, упоминания которого запрошены
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник запрошенного канала: «telegram» или «max»
    """
    limit: Annotated[int | None, Field(title='Limit')] = None
    """
    Размер страницы из запроса
    """
    offset: Annotated[int | None, Field(title='Offset')] = None
    """
    Смещение из запроса
    """
    mentions: Annotated[list[Mention] | None, Field(title='Mentions')] = None
    """
    Упоминания (свежие сверху)
    """


class Post(TrustatModel):
    """
    Актуальное состояние публикации.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    message_id: Annotated[int | None, Field(title='Message Id')] = None
    """
    ID сообщения
    """
    post_id: Annotated[str | None, Field(title='Post Id')] = None
    """
    Идентификатор поста в формате «<channel_id>_<message_id>»
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    date: Annotated[str | None, Field(title='Date')] = None
    """
    Дата публикации, UTC ISO-8601
    """
    edit_date: Annotated[str | None, Field(title='Edit Date')] = None
    """
    Дата последнего редактирования (UTC ISO-8601); null, если не редактировался
    """
    text: Annotated[str | None, Field(title='Text')] = None
    """
    Текущий текст поста
    """
    views: Annotated[int | None, Field(title='Views')] = None
    """
    Просмотры
    """
    forwards: Annotated[int | None, Field(title='Forwards')] = None
    """
    Репосты
    """
    replies: Annotated[int | None, Field(title='Replies')] = None
    """
    Комментарии
    """
    reactions_count: Annotated[int | None, Field(title='Reactions Count')] = None
    """
    Суммарное число реакций
    """
    is_deleted: Annotated[bool | None, Field(title='Is Deleted')] = None
    """
    Пост удалён
    """
    link: Annotated[str | None, Field(title='Link')] = None
    """
    Ссылка на пост (t.me/…)
    """
    forwarded_from: Annotated[Any, Field(title='Forwarded From')] = None
    """
    Источник пересылки, если это репост
    """
    media: Annotated[Any, Field(title='Media')] = None
    """
    Медиа-вложение, если есть
    """


class PostStat(TrustatModel):
    """
    Статистика вовлечённости публикации: просмотры, репосты, комментарии, реакции.
    """

    post_id: Annotated[str | None, Field(title='Post Id')] = None
    """
    Идентификатор поста «<channel_id>_<message_id>»
    """
    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    message_id: Annotated[int | None, Field(title='Message Id')] = None
    """
    ID сообщения
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    views: Annotated[int | None, Field(title='Views')] = None
    """
    Наиболее точное доступное число просмотров публикации
    """
    forwards: Annotated[int | None, Field(title='Forwards')] = None
    """
    Репосты
    """
    replies: Annotated[int | None, Field(title='Replies')] = None
    """
    Комментарии
    """
    reactions_count: Annotated[int | None, Field(title='Reactions Count')] = None
    """
    Суммарное число реакций
    """


class PostSummary(TrustatModel):
    """
    Краткая карточка публикации в результатах поиска.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    message_id: Annotated[int | None, Field(title='Message Id')] = None
    """
    ID сообщения
    """
    post_id: Annotated[str | None, Field(title='Post Id')] = None
    """
    Идентификатор поста «<channel_id>_<message_id>»
    """
    date: Annotated[str | None, Field(title='Date')] = None
    """
    Дата публикации, UTC ISO-8601
    """
    views: Annotated[int | None, Field(title='Views')] = None
    """
    Просмотры
    """
    text: Annotated[str | None, Field(title='Text')] = None
    """
    Текст поста
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """


class PostVersion(TrustatModel):
    """
    Одна сохранённая версия публикации из истории правок.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    message_id: Annotated[int | None, Field(title='Message Id')] = None
    """
    ID сообщения
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    version_date: Annotated[str | None, Field(title='Version Date')] = None
    """
    Когда эта версия была зафиксирована, UTC ISO-8601
    """
    post_date: Annotated[str | None, Field(title='Post Date')] = None
    """
    Дата исходной публикации поста, UTC ISO-8601
    """
    text: Annotated[str | None, Field(title='Text')] = None
    """
    Текст поста в этой версии
    """
    views: Annotated[int | None, Field(title='Views')] = None
    """
    Просмотры на момент фиксации версии
    """
    forwards: Annotated[int | None, Field(title='Forwards')] = None
    """
    Репосты на момент фиксации версии
    """
    replies: Annotated[int | None, Field(title='Replies')] = None
    """
    Комментарии на момент фиксации версии
    """
    reactions_count: Annotated[int | None, Field(title='Reactions Count')] = None
    """
    Суммарное число реакций на момент фиксации
    """
    is_deleted: Annotated[bool | None, Field(title='Is Deleted')] = None
    """
    Был ли пост удалён в этой версии
    """
    link: Annotated[str | None, Field(title='Link')] = None
    """
    Ссылка на пост (t.me/…)
    """
    forwarded_from: Annotated[Any, Field(title='Forwarded From')] = None
    """
    Источник пересылки, если это репост
    """
    media: Annotated[Any, Field(title='Media')] = None
    """
    Медиа-вложение, если есть
    """


class SubscribersPoint(TrustatModel):
    date: Annotated[str | None, Field(title='Date')] = None
    """
    Дата, YYYY-MM-DD
    """
    participants: Annotated[int | None, Field(title='Participants')] = None
    """
    Число подписчиков на эту дату
    """


class SubscribersSeries(TrustatModel):
    """
    Динамика подписчиков по дням/неделям/месяцам.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    group: Annotated[str | None, Field(title='Group')] = 'day'
    """
    Группировка: «day», «week» или «month»
    """
    days: Annotated[int | None, Field(title='Days')] = None
    """
    Глубина периода в днях (если не задан диапазон from/to_date)
    """
    points: Annotated[list[SubscribersPoint] | None, Field(title='Points')] = None
    """
    Точки временного ряда (по возрастанию даты)
    """


class TimelinePoint(TrustatModel):
    date: Annotated[str | None, Field(title='Date')] = None
    """
    Дата периода, YYYY-MM-DD
    """
    count: Annotated[int | None, Field(title='Count')] = None
    """
    Сколько объявлений в этом периоде
    """


class UsageInfo(TrustatModel):
    """
    Текущее потребление квоты по ключу.
    """

    plan: Annotated[str | None, Field(title='Plan')] = None
    """
    Тариф ключа (напр. «free», «pro»)
    """
    period: Annotated[str | None, Field(title='Period')] = None
    """
    Расчётный период, YYYY-MM
    """
    spent_requests: Annotated[str | None, Field(title='Spent Requests')] = None
    """
    Потрачено запросов за период в виде «использовано/лимит»
    """
    spent_unique_channels: Annotated[
        str | None, Field(title='Spent Unique Channels')
    ] = None
    """
    Уникальных каналов за период в виде «использовано/лимит»
    """
    spent_listing: Annotated[str | None, Field(title='Spent Listing')] = None
    """
    Результатов листинга (каталог/поиск) за период «использовано/лимит»
    """
    rps: Annotated[int | None, Field(title='Rps')] = None
    """
    Лимит запросов в секунду (rate limit)
    """
    scopes: Annotated[list[str] | None, Field(title='Scopes')] = None
    """
    Разрешённые этому ключу разделы (scopes)
    """


class ValidationError(TrustatModel):
    loc: Annotated[list[str | int] | None, Field(title='Location')] = None
    msg: Annotated[str | None, Field(title='Message')] = None
    type: Annotated[str | None, Field(title='Error Type')] = None
    input: Annotated[Any | None, Field(title='Input')] = None
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None


class VersionInfo(TrustatModel):
    version: Annotated[str | None, Field(title='Version')] = None
    """
    Версия сервиса
    """


class ViewsPoint(TrustatModel):
    date: Annotated[str | None, Field(title='Date')] = None
    """
    Дата, YYYY-MM-DD
    """
    value: Annotated[int | None, Field(title='Value')] = None
    """
    Значение метрики на эту дату
    """


class ViewsSeries(TrustatModel):
    """
    Динамика средних просмотров/охвата по дням.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    metric: Annotated[str | None, Field(title='Metric')] = None
    """
    Метрика: «views24» (просмотры за 24ч) или «views48» (охват за 48ч)
    """
    group: Annotated[str | None, Field(title='Group')] = 'day'
    """
    Группировка: «day», «week» или «month»
    """
    days: Annotated[int | None, Field(title='Days')] = None
    """
    Глубина периода в днях (если не задан диапазон from/to_date)
    """
    points: Annotated[list[ViewsPoint] | None, Field(title='Points')] = None
    """
    Точки временного ряда (по возрастанию даты)
    """


class AdFacets(TrustatModel):
    """
    Counts по каждому фасету для построения фильтров.
    """

    ad_format: Annotated[list[FacetBucket] | None, Field(title='Ad Format')] = None
    """
    По формату объявления
    """
    advertiser_type: Annotated[
        list[FacetBucket] | None, Field(title='Advertiser Type')
    ] = None
    """
    По типу рекламодателя
    """
    creative_lang: Annotated[list[FacetBucket] | None, Field(title='Creative Lang')] = (
        None
    )
    """
    По языку объявления
    """
    channel_country: Annotated[
        list[FacetBucket] | None, Field(title='Channel Country')
    ] = None
    """
    По стране канала показа (нормализовано)
    """
    channel_lang: Annotated[list[FacetBucket] | None, Field(title='Channel Lang')] = (
        None
    )
    """
    По языку канала показа
    """
    channel_category_id: Annotated[
        list[FacetBucket] | None, Field(title='Channel Category Id')
    ] = None
    """
    По категории канала показа
    """
    button_text: Annotated[list[FacetBucket] | None, Field(title='Button Text')] = None
    """
    По тексту кнопки (CTA)
    """
    color_id: Annotated[list[FacetBucket] | None, Field(title='Color Id')] = None
    """
    По акцентному цвету
    """


class AdSearchList(TrustatModel):
    """
    Страница результатов поиска по рекламе.
    """

    total: Annotated[int | None, Field(title='Total')] = None
    """
    Примерное число подходящих объявлений (точно до порога; дальше — нижняя оценка)
    """
    limit: Annotated[int | None, Field(title='Limit')] = None
    """
    Размер страницы из запроса
    """
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    """
    Курсор следующей страницы; null, если объявлений больше нет
    """
    ads: Annotated[list[AdSummary] | None, Field(title='Ads')] = None
    """
    Объявления на этой странице
    """


class AdsTimeline(TrustatModel):
    """
    Динамика объёма рекламы по времени.
    """

    group: Annotated[str | None, Field(title='Group')] = None
    """
    Группировка: «day», «week» или «month»
    """
    date_field: Annotated[str | None, Field(title='Date Field')] = None
    """
    По какому полю даты построен ряд: «first_seen» или «last_seen»
    """
    points: Annotated[list[TimelinePoint] | None, Field(title='Points')] = None
    """
    Точки ряда (по возрастанию даты)
    """


class CategoriesDict(TrustatModel):
    categories: Annotated[list[CategoryDict] | None, Field(title='Categories')] = None
    """
    Справочник категорий
    """


class ChannelBatch(TrustatModel):
    """
    Ответ батч-запроса по списку ID.
    """

    requested: Annotated[int | None, Field(title='Requested')] = None
    """
    Сколько ID запрошено (после дедупликации)
    """
    found: Annotated[int | None, Field(title='Found')] = None
    """
    Сколько каналов найдено
    """
    channels: Annotated[list[ChannelInfo] | None, Field(title='Channels')] = None
    """
    Найденные каналы (порядок соответствует запросу)
    """


class ChannelPostsFeed(TrustatModel):
    """
    Хронологическая лента постов канала (свежие сверху) с курсорной пагинацией.
    """

    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    posts: Annotated[list[PostSummary] | None, Field(title='Posts')] = None
    """
    Посты на этой странице
    """
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    """
    Курсор для следующей страницы; null, если постов больше нет
    """


class CountriesDict(TrustatModel):
    countries: Annotated[list[CountryDict] | None, Field(title='Countries')] = None
    """
    Справочник стран
    """


class EnvelopeAdFacets(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: AdFacets | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeAdSearchList(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: AdSearchList | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeAdsTimeline(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: AdsTimeline | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeCategoriesDict(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: CategoriesDict | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeChannelBatch(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: ChannelBatch | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeChannelPostsFeed(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: ChannelPostsFeed | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeCountriesDict(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: CountriesDict | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeForwardList(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: ForwardList | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeHealthStatus(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: HealthStatus | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeLanguagesDict(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: LanguagesDict | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeMentionList(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: MentionList | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopePostStat(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: PostStat | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopePost(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: Post | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeSubscribersSeries(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: SubscribersSeries | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeUsageInfo(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: UsageInfo | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeVersionInfo(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: VersionInfo | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopeViewsSeries(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: ViewsSeries | None = None
    """
    Полезная нагрузка ответа
    """


class HTTPValidationError(TrustatModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class LookupResponse(TrustatModel):
    """
    Результаты резолвера. Обычно один; при source=all и коллизии — несколько кандидатов.
    """

    results: Annotated[list[LookupResult] | None, Field(title='Results')] = None
    """
    Канонические кандидаты (≥1)
    """


class PostHistory(TrustatModel):
    """
    История правок поста.
    """

    post_id: Annotated[str | None, Field(title='Post Id')] = None
    """
    Идентификатор поста «<channel_id>_<message_id>»
    """
    channel_id: Annotated[int | None, Field(title='Channel Id')] = None
    """
    ID канала
    """
    message_id: Annotated[int | None, Field(title='Message Id')] = None
    """
    ID сообщения
    """
    source: Annotated[str | None, Field(title='Source')] = None
    """
    Источник: «telegram» или «max»
    """
    versions_count: Annotated[int | None, Field(title='Versions Count')] = None
    """
    Сколько версий сохранено
    """
    versions: Annotated[list[PostVersion] | None, Field(title='Versions')] = None
    """
    Версии поста (свежие сверху)
    """


class PostSearchList(TrustatModel):
    """
    Страница результатов поиска по постам.
    """

    total: Annotated[int | None, Field(title='Total')] = None
    """
    Примерное число подходящих постов (точно до порога; дальше — нижняя оценка)
    """
    limit: Annotated[int | None, Field(title='Limit')] = None
    """
    Размер страницы из запроса
    """
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    """
    Курсор следующей страницы; null, если постов больше нет (или достигнут потолок глубины — сузьте фильтр)
    """
    posts: Annotated[list[PostSummary] | None, Field(title='Posts')] = None
    """
    Найденные посты
    """


class EnvelopeLookupResponse(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: LookupResponse | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopePostHistory(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: PostHistory | None = None
    """
    Полезная нагрузка ответа
    """


class EnvelopePostSearchList(TrustatModel):
    status: Annotated[str | None, Field(title='Status')] = 'ok'
    """
    Всегда «ok» для успешного ответа
    """
    response: PostSearchList | None = None
    """
    Полезная нагрузка ответа
    """
